name: Auto-OJ-Answer
# 处理Issue, 将Issue中的problem自动爬取答案

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone仓库
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖, 执行代码
        run: |
          pip install --upgrade pip
          pip install httpx[http2]
          pip install pygithub
          pip install -r requirements.txt
          python3 issue.py ${{ secrets.ACCESS_TOKEN }}

      - name: 提交到GitHub
        env:
          GITHUB_REPO: github.com/YangRucheng/XTU-OnlineJudge-Answer
        run: |
          git config user.name "Auto Get OJ Answer"
          git config user.email "admin@yangrucheng.top"
          git add .
          git commit -m "GitHub Actions Auto Get Answer From Issue at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" main:main
